import { defineStore } from "pinia";

export const useBannerStore = defineStore('banners',{
    state: () =>{
        return{
            banners: {
                sneakerBanner:{
                    image:[
                        './src/assets/images/Banner/SneakerBanner/spiderman.jpg',
                        './src/assets/images/Banner/SneakerBanner/sambas_banner.jpg',
                        './src/assets/images/Banner/SneakerBanner/lostandfound.jpg',
                        './src/assets/images/Banner/SneakerBanner/panda.jpg',
                        './src/assets/images/Banner/SneakerBanner/Onitsuka.jpg',
                    ]
                },
                accessoryBanner:{
                    image:[
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner1.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner2.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner3.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner4.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner5.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner6.jpg',
                        './src/assets/images/Banner/AccessoriesBanner/bagbanner7.jpg',
                    ]
                },
                menswearBanner:{
                    image:[
                        './src/assets/images/Banner/MenswearBanner/Louis_Vuitton.jpg',
                        './src/assets/images/Banner/MenswearBanner/Gucci.jpg',
                        './src/assets/images/Banner/MenswearBanner/gucci1.jpg',
                        './src/assets/images/Banner/MenswearBanner/Dior1.jpg',
                        './src/assets/images/Banner/MenswearBanner/Valentino.jpg',
                        './src/assets/images/Banner/MenswearBanner/Balenciaga.jpg',
                    ]
                },
                womenswearBanner:{
                    image:[
                        './src/assets/images/Banner/WomenswearBanner/WomenwearBanner3.png',
                        './src/assets/images/Banner/WomenswearBanner/WomenwearBanner2.png',
                        './src/assets/images/Banner/WomenswearBanner/WomenwearBanner5.png',
                        './src/assets/images/Banner/WomenswearBanner/WomenwearBanner4.png',
                        './src/assets/images/Banner/WomenswearBanner/WomenwearBanner1.png',
                    ]
                },
                collectiblesBanner:{
                    image:[
                        './src/assets/images/Banner/CollectiblesBanner/aespa.jpeg',
                        './src/assets/images/Banner/CollectiblesBanner/twice.jpg',
                        './src/assets/images/Banner/CollectiblesBanner/nctdream.jpeg',
                        './src/assets/images/Banner/CollectiblesBanner/illit.jpeg',
                        './src/assets/images/Banner/CollectiblesBanner/bibi.jpeg',
                        './src/assets/images/Banner/CollectiblesBanner/riize.png',
                        './src/assets/images/Banner/CollectiblesBanner/enhypen.jpg',
                    ]
                },
            }
        }
    }
})
