import { defineStore } from "pinia";

export const useSneakerStore = defineStore("sneakerStore",{
    state: () => ({
        products: [
            {
            category: "sneaker",
            brand_name: "Air Jordan 1 Retro High",
            product_name: "Yellow Ochre",
            price: "$133 Starting",
            product_id: "AJ1_YLO",
            product_type: "sneaker",
            product_status: "Available For Pre-order",
            thumbNail:
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image1.jpg",
            productImages: [
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image1.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image2.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image3.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image4.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image5.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/image6.jpg",
            ],
            detailImages: [
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/detail1.jpg",
                "/src/assets/images/DetailImage/Sneakers/YellowOchre/detail2.jpg",
            ],
            description: `Step into the perfect blend of classic and contemporary with this remastered Air Jordan 1. The bold interplay of Yellow Ochre and deep black creates a striking contrast against the smooth, tumbled Sail leather, delivering a look that's as clean as it is sophisticated.
                                    Every detail has been thoughtfully refined, from the premium materials to the vintage-inspired branding, evoking a sense of timelessness. This is where heritage meets innovation—a seamless
                                    fusion of old-school charm and modern design. With a finish as smooth as MJ's signature fadeaway, this AJ1 stands as a true testament to the legacy of greatness, designed for those who appreciate
                                    both tradition and bold, fresh style.`,
            tags: ["new"],
            productSizes: [
                { size: "US 4", price: 177 },
                { size: "US 5", price: 142 },
                { size: "US 6", price: 148 },
                { size: "US 7", price: 181 },
                { size: "US 8", price: 133 },
                { size: "US 9", price: 195 },
                { size: "US 10", price: 206 },
                { size: "US 11", price: 286 },
                { size: "US 12", price: 245 },
                { size: "US 13", price: 216 },
                { size: "US 14", price: 209 },
            ],
            },
            {
            category: "sneaker",
            brand_name: "SB Dunk Low",
            product_name: "Yuto x Wolf Grey",
            price: "$201 Starting",
            product_id: "SBD_Yuto",
            product_type: "sneaker",
            product_status: "Available For Pre-order",
            thumbNail: "/src/assets/images/DetailImage/Sneakers/Yuto/image1.jpg",
            productImages: [
                "/src/assets/images/DetailImage/Sneakers/Yuto/image1.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/image2.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/image3.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/image4.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/image5.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/image6.jpg",
            ],
            detailImages: [
                "/src/assets/images/DetailImage/Sneakers/Yuto/detail1.jpg",
                "/src/assets/images/DetailImage/Sneakers/Yuto/detail2.jpg",
            ],
            description: `Not many can claim to be the first. Yuto Horigome is one of the few. Crafted to the champion's specs, the Nike SB Dunk Low x Yuto brings you a skate-worthy design that taps into the places where he first
                                    developed his craft. Delivering the gold standard of skate shoes (and marked with Yuto's family crest), it lets you glide between casually spinning tricks on vert and going big in the streets—just like Yuto.`,
            tags: ["new"],
            productSizes: [
                { size: "US 4", price: 201 },
                { size: "US 5", price: 211 },
                { size: "US 6", price: 263 },
                { size: "US 7", price: 276 },
                { size: "US 8", price: 274 },
                { size: "US 9", price: 311 },
                { size: "US 10", price: 319 },
                { size: "US 11", price: 363 },
                { size: "US 12", price: 341 },
                { size: "US 13", price: 399 },
                { size: "US 14", price: 385 },
            ],
            },
            {
            category: "sneaker",
            brand_name: "Air Jordan 1 High OG",
            product_name: "Spiderman Next Chapter",
            price: "$94 Starting",
            product_type: "sneaker",
            product_id: "AJ1_SPM",
            product_status: "Available Instock",
            thumbNail:
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image1.jpg",
            productImages: [
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image1.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image2.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image3.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image4.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image5.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/image6.jpg",
            ],
            detailImages: [
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/detail1.jpg",
                "/src/assets/images/DetailImage/Sneakers/AJ1Spiderman/detail2.jpg",
            ],
            description: `You don't need a cape to take flight—just your AJ1s. You know, the ones seen on Miles in "Spider-Man: Across the Spider-Verse", exclusively in cinemas. This fresh take on the iconic Chicago
                                    colourway boasts a mix of materials, including lustrous leather and soft suede. The world is waiting, so step on in.`,
            tags: ["new"],
            productSizes: [
                { size: "US 4", price: 177 },
                { size: "US 5", price: 142 },
                { size: "US 6", price: 148 },
                { size: "US 7", price: 181 },
                { size: "US 8", price: 133 },
                { size: "US 9", price: 195 },
                { size: "US 10", price: 206 },
                { size: "US 11", price: 286 },
                { size: "US 12", price: 245 },
                { size: "US 13", price: 216 },
                { size: "US 14", price: 209 },
            ],
            },
            {
                category: "sneaker",
                brand_name: "New Balance",
                product_name: "Nimbus Cloud 574 Core",
                price: "$60 Starting",
                product_type: "sneaker",
                product_id: "NB_574",
                product_status: "Available Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/NewBalance574/thumbnail_image.png",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/detail1.png',
                    '/src/assets/images/DetailImage/Sneakers/NewBalance574/detail2.png',
                ],
                description: `The most New Balance shoe ever says it all, right? No, actually. The 574 might be our unlikeliest icon. The 574 was built to be a reliable shoe that could do a lot of different things well rather than as a platform
                            for revolutionary technology, or as a premium materials showcase. This unassuming, unpretentious versatility is exactly what launched the 574 into the ranks of all-time greats.

                            As hybrid road/trail design built on a wider last than the previous generation’s narrow racing silhouettes, the 574 offered a uniquely versatile mix of new, different, uncomplicated, rugged, durable, and
                            comfortable that was adopted as a closet staple across the globe. That’s why today, the 574 is synonymous with the boundary defying New Balance style, and worn by anyone. With the 574 for kids, the same
                            As hybrid road/trail design built on a wider last than the previous generation’s narrow racing silhouettes, the 574 offered a uniquely versatile mix of new, different, uncomplicated, rugged, durable, and
                            comfortable that was adopted as a closet staple across the globe. That’s why today, the 574 is synonymous with the boundary defying New Balance style, and worn by anyone. With the 574 for kids, the same
                            style inspiration is pared down for growing feet.`,
                tags: ["new"],
                productSizes: [
                    {size: "US 4", price: 60},
                    {size: "US 5", price: 64},
                    {size: "US 6", price: 71},
                    {size: "US 7", price: 71},
                    {size: "US 8", price: 72},
                    {size: "US 9", price: 73},
                    {size: "US 10", price: 72},
                    {size: "US 11", price: 82},
                    {size: "US 12", price: 83},
                    {size: "US 13", price: 82},
                    {size: "US 14", price: 88},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Jordan 1 Retro High OG",
                product_name: "Chicago Lost and Found",
                price: "$208 Starting",
                product_type: "sneaker",
                product_id: "AJ1LnF",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AJ1LnF/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LnF/detail2.jpg',
                ],
                description: `Dressed in a Varsity Red, Black, Sail, and Muslin colour scheme. This offering of the Air Jordan 1 comes built with cracked leather featuring a White leather base with Red overlays and Black on the Wings, Swooshes, and collar. Other details includes Muslin tongues, Nike Air branding atop a White midsole and Red rubber outsole.
                            The pair is a homage to the days when you’d find a pair of DS 85 Chicago Jordan 1s in their stock housed in aged boxes with replacement Orange Nike lids (AJKO lids). The shoes also come with special throwback graphic tissue paper, sale stickers, and vintage-style invoice receipt.`,
                tags: ["recommended","new"],
                productSizes: [
                    {size: "US 4", price: 208},
                    {size: "US 5", price: 240},
                    {size: "US 6", price: 251},
                    {size: "US 7", price: 259},
                    {size: "US 8", price: 298},
                    {size: "US 9", price: 310},
                    {size: "US 10", price: 325},
                    {size: "US 11", price: 324},
                    {size: "US 12", price: 345},
                    {size: "US 13", price: 311},
                    {size: "US 14", price: 345},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Jordan 1 Low",
                product_name: "Vintage UNC Grey",
                price: "$98 Starting",
                product_type: "sneaker",
                product_id: "AJ1LowTokyo",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1LowTokyo/detail2.jpg',
                ],
                description: "Can you believe it's been over 25 years since MJ first visited Tokyo? To honour that history, this special AJ1 takes you back to the beginning with a colourway inspired by Hoop Heroes tour merch. Dutch Blue graces the outsole and toe, Smoke Grey covers the upper and heel, while pops of Kumquat accent the Wings logo and insole. Aged touches on the midsole and an exposed foam tongue add a perfectly worn-in look. Just say you've been wearing 'em since '96.",
                tags: ["recommended","new"],
                productSizes: [
                    {size: "US 4", price: 106},
                    {size: "US 5", price: 105},
                    {size: "US 6", price: 180},
                    {size: "US 7", price: 126},
                    {size: "US 8", price: 102},
                    {size: "US 9", price: 98},
                    {size: "US 10", price: 134},
                    {size: "US 11", price: 169},
                    {size: "US 12", price: 242},
                    {size: "US 13", price: 342},
                    {size: "US 14", price: 345},
                ]
            },
            {
                category: "sneaker",
                brand_name: "ACG Air",
                product_name: "Retro Vintage",
                price: "$75 Starting",
                product_type: "sneaker",
                product_id: "ACGAir",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/ACGAir/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/ACGAir/detail2.jpg',
                ],

                description: "The ACG Air Retro is a sleek, high-performance sneaker that combines Nike's renowned All Conditions Gear (ACG) technology with a retro-inspired design. Built for versatility, comfort, and durability, this shoe seamlessly blends style with function, making it ideal for urban exploration or outdoor adventures. With a rugged outsole, cushioned midsole, and weather-ready features, the ACG Air Retro is the perfect choice for those who demand both performance and fashion in their footwear.",
                tags: ["recommended","new"],
                productSizes: [
                    {size: "US 4", price: 185},
                    {size: "US 5", price: 159},
                    {size: "US 6", price: 119},
                    {size: "US 7", price: 80},
                    {size: "US 8", price: 82},
                    {size: "US 9", price: 82},
                    {size: "US 10", price: 75},
                    {size: "US 11", price: 84},
                    {size: "US 12", price: 96},
                    {size: "US 13", price: 85},
                    {size: "US 14", price: 125},
                ]
            },
            {
                brand_name: "Air Jordan 1 Retro High",
                category: "sneaker",
                product_name: "Mocha",
                price: "$285 Starting",
                product_type: "sneaker",
                product_id: "AJ1Mocha",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1Mocha/detail2.jpg',
                ],

                description: "The Jordan 1 Mocha brings a fresh twist to the iconic silhouette, featuring a sleek, earthy colorway that blends premium materials and a laid-back design. With its smooth leather uppers in rich mocha brown, white accents, and classic Nike Swoosh, this sneaker offers a refined, versatile look perfect for both everyday wear and stylish streetwear. The low-top profile ensures a comfortable fit, while the timeless Jordan 1 design remains at the heart of this effortlessly cool sneaker. Whether you're a collector or simply a fan of premium kicks, the Jordan 1 Retro High Mocha is a must-have addition to your rotation.",
                tags: ["recommended","new"],
                productSizes: [
                    {size: "US 4", price: 425},
                    {size: "US 5", price: 469},
                    {size: "US 6", price: 505},
                    {size: "US 7", price: 306},
                    {size: "US 8", price: 285},
                    {size: "US 9", price: 294},
                    {size: "US 10", price: 332},
                    {size: "US 11", price: 349},
                    {size: "US 12", price: 329},    
                    {size: "US 13", price: 367},
                    {size: "US 14", price: 349},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Force 1",
                product_name: "Off-White",
                price: "$102 Starting",
                product_type: "sneaker",
                product_id: "AF1_OffWhite",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/detail2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_OffWhite/detail3.jpg',
                ],

                description:"The Air Force 1 Off-White is a standout collaboration between Nike and Virgil Abloh's Off-White brand, merging classic design with cutting-edge street style. Featuring a clean, minimalist white leather upper, the sneaker is elevated by signature Off-White details, including bold “AIR” branding, the iconic zip tie, and unique stitching and deconstructed elements. The translucent Swoosh and subtle text on the side provide a fresh, industrial look that pays homage to Abloh’s distinctive aesthetic. With its perfect mix of high fashion and basketball heritage, the Air Force 1 Off-White is a must-have for sneakerheads and fashion-forward individuals alike.",
                tags: ["collab","recommended","new"],
                productSizes: [
                    {size: "US 4", price: 105},
                    {size: "US 5", price: 102},
                    {size: "US 6", price: 123},
                    {size: "US 7", price: 151},
                    {size: "US 8", price: 169},
                    {size: "US 9", price: 142},
                    {size: "US 10", price: 157},
                    {size: "US 11", price: 146},
                    {size: "US 12", price: 168},
                    {size: "US 13", price: 128},
                    {size: "US 14", price: 150},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Jordan 1 Low OG SP",
                product_name: "Travis Scott Reverse Mocha",
                price: "$1,069 Starting",
                product_type: "sneaker",
                product_id: "AJ1_TravMocha",
                product_status: "Available For Pre-order",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ1TravisMocha/detail2.jpg',
                ],
                description: "The Air Jordan 1 Low OG SP Travis Scott Reverse Mocha is a highly anticipated release that continues the collaboration between Nike and hip-hop superstar Travis Scott. Featuring a premium blend of white leather and rich reverse mocha suede, the sneaker reimagines the iconic Jordan 1 Low silhouette with a striking color contrast. The signature Cactus Jack branding appears subtly on the heel and insole, while the oversized lateral Swoosh adds a bold, off-kilter touch that’s become a hallmark of Travis' designs. With a perfect balance of streetwear style and high-end craftsmanship, the Reverse Mocha offers a sleek, versatile look that pairs effortlessly with any outfit, making it a must-have for sneakerheads and fashion enthusiasts alike.",
                tags: ["collab","recommended","new"],
                productSizes: [
                    {size: "US 4", price: 1372},
                    {size: "US 5", price: 1226},
                    {size: "US 6", price: 1451},
                    {size: "US 7", price: 1356},
                    {size: "US 8", price: 1127},
                    {size: "US 9", price: 1293},
                    {size: "US 10", price: 1400},
                    {size: "US 11", price: 1347},
                    {size: "US 12", price: 1372},
                    {size: "US 13", price: 1069},
                    {size: "US 14", price: 1201},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Jordan 5 Retro",
                product_name: "Off-White Muslim",
                price: "$535 Starting",
                product_type: "sneaker",
                product_id: "AJ5Abloh",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AJ5ABloh/detail2.jpg',
                ],
                description: "The Air Jordan 5 Retro Off-White Muslim is a bold and unique collaboration that blends iconic Jordan design with the visionary touch of Off-White’s Virgil Abloh. Featuring a striking mix of neutral tones, premium materials, and distinct design cues, this release combines Jordan's classic silhouette with Off-White's signature details, including translucent accents, bold AIR branding, and zip-tie tags. The Muslim colorway incorporates subtle earthy hues that reflect cultural influences while paying homage to craftsmanship and authenticity. With its attention-grabbing style and innovative design, the Air Jordan 5 Retro Off-White Muslim is not just a sneaker—it's a statement piece that stands at the intersection of streetwear, art, and heritage.",
                tags: ["collab","recommended","new"],
                productSizes: [
                    {size: "US 4", price: 535},
                    {size: "US 5", price: 632},
                    {size: "US 6", price: 894},
                    {size: "US 7", price: 600},
                    {size: "US 8", price: 525},
                    {size: "US 9", price: 678},
                    {size: "US 10", price: 797},
                    {size: "US 11", price: 839},
                    {size: "US 12", price: 912},
                    {size: "US 13", price: 1083},
                    {size: "US 14", price: 1347},
                ]
            },
            {
                category: "sneaker",
                brand_name: "Air Force 1",
                product_name: "Peace Maker",
                price: "$208 Starting",
                product_type: "sneaker",
                product_id: "AF1_PMaker",
                product_status: "Available For Instock",
                thumbNail: "/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image1.jpg",
                productImages: [
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image4.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image5.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/image6.jpg',
                ],
                detailImages:[
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/detail1.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/detail2.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/detail3.jpg',
                    '/src/assets/images/DetailImage/Sneakers/AF1_PMaker/detail4.jpg',
                ],

                description: "The Air Force 1 Peace Maker is a fresh and stylish take on the iconic silhouette, combining classic design with modern, meaningful details. This edition features premium materials and a bold colorway, with the standout Peace Maker theme showcased through symbolic graphics and subtle embellishments. The sneaker's clean leather upper is paired with unique stitching and custom logos that reflect a message of unity and positivity. With its versatile look and statement-making details, the Air Force 1 Peace Maker is perfect for those who want to stand out while promoting a message of peace and inclusivity.",
                tags: ["collab","recommended","new"],
                productSizes: [
                    {size: "US 4", price: 1372},
                    {size: "US 5", price: 1226},
                    {size: "US 6", price: 1451},
                    {size: "US 7", price: 1356},
                    {size: "US 8", price: 1127},
                    {size: "US 9", price: 1293},
                    {size: "US 10", price: 1400},
                    {size: "US 11", price: 1347},
                    {size: "US 12", price: 1372},
                    {size: "US 13", price: 1069},
                    {size: "US 14", price: 1201},
                ]
            },
        ],
    })
})
